using System.Data.Common;
using AssetManagement.Data;
using Microsoft.EntityFrameworkCore;

namespace AssetManagement.Services;

public static class DatabaseInitializer
{
    private enum DatabaseProvider
    {
        Sqlite,
        Postgres
    }

    private sealed record ColumnSchema(string Name, string SqliteDefinition, string PostgresDefinition);

    private sealed record TableSchema(
        string Name,
        string PrimaryKeyColumn,
        bool PrimaryKeyAutoIncrements,
        IReadOnlyList<ColumnSchema> Columns);

    private sealed record ProviderSql(string Sqlite, string Postgres);

    private sealed record ProviderText(string Sqlite, string Postgres);

    private sealed record IndexSchema(
        ProviderText Name,
        string TableName,
        bool Unique,
        IReadOnlyList<string> Columns,
        ProviderText? Expression = null);

    private static readonly TableSchema[] Tables =
    [
        new("Users", "Id", true,
        [
            new("Id", "INTEGER NOT NULL", "integer GENERATED BY DEFAULT AS IDENTITY"),
            new("Username", "TEXT NOT NULL", "text NOT NULL"),
            new("PasswordHash", "TEXT NOT NULL", "text NOT NULL"),
            new("FullName", "TEXT NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"),
            new("Role", "TEXT NOT NULL DEFAULT 'User'", "text NOT NULL DEFAULT 'User'"),
            new("MilitaryId", "TEXT NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''")
        ]),
        new("Items", "Id", true,
        [
            new("Id", "INTEGER NOT NULL", "integer GENERATED BY DEFAULT AS IDENTITY"),
            new("Name", "TEXT NOT NULL", "text NOT NULL"),
            new("Quantity", "INTEGER NOT NULL", "integer NOT NULL"),
            new("AssetTag", "TEXT NOT NULL", "text NOT NULL"),
            new("Nature", "TEXT NOT NULL", "text NOT NULL"),
            new("Location", "TEXT NOT NULL", "text NOT NULL"),
            new("Condition", "TEXT NOT NULL", "text NOT NULL"),
            new("Notes", "TEXT NOT NULL", "text NOT NULL"),
            new("PhotoFileName", "TEXT NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"),
            new("PhotoContentType", "TEXT NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"),
            new("IsDischarged", "INTEGER NOT NULL DEFAULT 0", "boolean NOT NULL DEFAULT false"),
            new("DischargedAt", "TEXT NULL", "timestamp with time zone NULL"),
            new("ResponsiblePerson", "TEXT NULL", "text NULL"),
            new("CreatedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL"),
            new("UpdatedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL")
        ]),
        new("Movements", "Id", true,
        [
            new("Id", "INTEGER NOT NULL", "integer GENERATED BY DEFAULT AS IDENTITY"),
            new("ItemId", "INTEGER NOT NULL", "integer NOT NULL"),
            new("DestinationItemId", "INTEGER NULL", "integer NULL"),
            new("ItemName", "TEXT NOT NULL", "text NOT NULL"),
            new("Quantity", "INTEGER NOT NULL", "integer NOT NULL"),
            new("MovementType", "TEXT NOT NULL", "text NOT NULL"),
            new("FromLocation", "TEXT NOT NULL", "text NOT NULL"),
            new("ToLocation", "TEXT NOT NULL", "text NOT NULL"),
            new("FromCondition", "TEXT NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"),
            new("ToCondition", "TEXT NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"),
            new("FromIsDischarged", "INTEGER NOT NULL DEFAULT 0", "boolean NOT NULL DEFAULT false"),
            new("ToIsDischarged", "INTEGER NOT NULL DEFAULT 0", "boolean NOT NULL DEFAULT false"),
            new("DestinationType", "TEXT NOT NULL", "text NOT NULL"),
            new("DestinationPerson", "TEXT NOT NULL", "text NOT NULL"),
            new("OriginPerson", "TEXT NOT NULL", "text NOT NULL"),
            new("Notes", "TEXT NOT NULL", "text NOT NULL"),
            new("PerformedByUserId", "INTEGER NOT NULL", "integer NOT NULL"),
            new("PerformedByUserName", "TEXT NOT NULL", "text NOT NULL"),
            new("CreatedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL")
        ]),
        new("AuditLogs", "Id", true,
        [
            new("Id", "INTEGER NOT NULL", "integer GENERATED BY DEFAULT AS IDENTITY"),
            new("Timestamp", "TEXT NOT NULL", "timestamp with time zone NOT NULL"),
            new("ActorUserId", "INTEGER NOT NULL", "integer NOT NULL"),
            new("ActorUserName", "TEXT NOT NULL", "text NOT NULL"),
            new("Action", "TEXT NOT NULL", "text NOT NULL"),
            new("EntityType", "TEXT NOT NULL", "text NOT NULL"),
            new("EntityId", "TEXT NOT NULL", "text NOT NULL"),
            new("Summary", "TEXT NOT NULL", "text NOT NULL"),
            new("Details", "TEXT NOT NULL", "text NOT NULL")
        ]),
        new("UserNotes", "Id", true,
        [
            new("Id", "INTEGER NOT NULL", "integer GENERATED BY DEFAULT AS IDENTITY"),
            new("UserId", "INTEGER NOT NULL", "integer NOT NULL"),
            new("Title", "TEXT NOT NULL", "text NOT NULL"),
            new("Content", "TEXT NOT NULL", "text NOT NULL"),
            new("Tags", "TEXT NOT NULL", "text NOT NULL"),
            new("CreatedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL"),
            new("UpdatedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL")
        ]),
        new("LocationOptions", "Id", true,
        [
            new("Id", "INTEGER NOT NULL", "integer GENERATED BY DEFAULT AS IDENTITY"),
            new("Name", "TEXT NOT NULL", "text NOT NULL"),
            new("CreatedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL")
        ]),
        new("AppLocks", "Name", false,
        [
            new("Name", "TEXT NOT NULL", "text NOT NULL"),
            new("TouchedAt", "TEXT NOT NULL", "timestamp with time zone NOT NULL")
        ])
    ];

    private static readonly ProviderSql AppLocksSeedSql = new(
        """
        INSERT OR IGNORE INTO "AppLocks" ("Name", "TouchedAt")
        VALUES ('Items', CURRENT_TIMESTAMP);
        """,
        """
        INSERT INTO "AppLocks" ("Name", "TouchedAt")
        VALUES ('Items', now())
        ON CONFLICT ("Name") DO NOTHING;
        """);

    private static readonly (string Table, string Column)[] EnsuredColumns =
    [
        ("Users", "FullName"),
        ("Users", "Role"),
        ("Users", "MilitaryId"),
        ("Items", "PhotoFileName"),
        ("Items", "PhotoContentType"),
        ("Items", "IsDischarged"),
        ("Items", "DischargedAt"),
        ("Items", "ResponsiblePerson"),
        ("Movements", "FromCondition"),
        ("Movements", "ToCondition"),
        ("Movements", "FromIsDischarged"),
        ("Movements", "ToIsDischarged"),
        ("Movements", "DestinationItemId")
    ];

    private static readonly IndexSchema[] Indexes =
    [
        new(
            new("IX_Users_Username_NoCase", "IX_Users_Username_Lower"),
            "Users",
            true,
            ["Username"],
            new($"{QuoteIdentifier("Username")} COLLATE NOCASE", $"lower({QuoteIdentifier("Username")})")),
        new(
            new("IX_LocationOptions_Name_NoCase", "IX_LocationOptions_Name_Lower"),
            "LocationOptions",
            true,
            ["Name"],
            new($"{QuoteIdentifier("Name")} COLLATE NOCASE", $"lower({QuoteIdentifier("Name")})")),
        new(new("IX_Movements_ItemId", "IX_Movements_ItemId"), "Movements", false, ["ItemId"]),
        new(new("IX_Movements_DestinationItemId", "IX_Movements_DestinationItemId"), "Movements", false, ["DestinationItemId"]),
        new(new("IX_UserNotes_UserId", "IX_UserNotes_UserId"), "UserNotes", false, ["UserId"]),
        new(
            new("IX_AuditLogs_ActorUserId_EntityType_EntityId", "IX_AuditLogs_ActorUserId_EntityType_EntityId"),
            "AuditLogs",
            false,
            ["ActorUserId", "EntityType", "EntityId"])
    ];

    public static async Task InitializeAsync(AppDbContext context)
    {
        if (context.Database.IsSqlite())
        {
            await context.Database.EnsureCreatedAsync();
            await InitializeSqliteAsync(context);
            return;
        }

        if (context.Database.IsNpgsql())
        {
            await InitializePostgresAsync(context);
            return;
        }

        throw new InvalidOperationException("Provedor de banco de dados não suportado.");
    }

    private static async Task InitializeSqliteAsync(AppDbContext context)
    {
        await EnsureTablesAsync(context, DatabaseProvider.Sqlite);
        await EnsureColumnsAsync(context, DatabaseProvider.Sqlite);
        await ExecuteProviderSqlAsync(context, AppLocksSeedSql, DatabaseProvider.Sqlite);
        await EnsureIndexesAsync(context, DatabaseProvider.Sqlite);
    }

    private static async Task InitializePostgresAsync(AppDbContext context)
    {
        await EnsureTablesAsync(context, DatabaseProvider.Postgres);
        await EnsureColumnsAsync(context, DatabaseProvider.Postgres);
        await ExecuteProviderSqlAsync(context, AppLocksSeedSql, DatabaseProvider.Postgres);
        await EnsureIndexesAsync(context, DatabaseProvider.Postgres);
    }

    private static async Task EnsureColumnsAsync(AppDbContext context, DatabaseProvider provider)
    {
        foreach (var (tableName, columnName) in EnsuredColumns)
        {
            var definition = GetColumnDefinition(tableName, columnName, provider);

            if (provider == DatabaseProvider.Postgres)
            {
                var sql = $"ALTER TABLE {QuoteIdentifier(tableName)} ADD COLUMN IF NOT EXISTS {QuoteIdentifier(columnName)} {definition};";
                await context.Database.ExecuteSqlRawAsync(sql);
                continue;
            }

            await EnsureSqliteColumnAsync(context, tableName, columnName, definition);
        }
    }

    private static string GetColumnDefinition(string tableName, string columnName, DatabaseProvider provider)
    {
        var table = Tables.First(x => x.Name == tableName);
        var column = table.Columns.First(x => x.Name == columnName);
        return provider == DatabaseProvider.Sqlite ? column.SqliteDefinition : column.PostgresDefinition;
    }

    private static async Task EnsureTablesAsync(AppDbContext context, DatabaseProvider provider)
    {
        foreach (var table in Tables)
            await context.Database.ExecuteSqlRawAsync(BuildCreateTableSql(table, provider));
    }

    private static async Task EnsureIndexesAsync(AppDbContext context, DatabaseProvider provider)
    {
        foreach (var index in Indexes)
            await context.Database.ExecuteSqlRawAsync(BuildCreateIndexSql(index, provider));
    }

    private static Task ExecuteProviderSqlAsync(AppDbContext context, ProviderSql sql, DatabaseProvider provider) =>
        context.Database.ExecuteSqlRawAsync(SelectSql(sql, provider));

    private static string BuildCreateTableSql(TableSchema table, DatabaseProvider provider)
    {
        var lines = table.Columns
            .Select(column => BuildColumnSql(table, column, provider))
            .ToList();

        if (provider == DatabaseProvider.Postgres)
            lines.Add($"CONSTRAINT {QuoteIdentifier($"PK_{table.Name}")} PRIMARY KEY ({QuoteIdentifier(table.PrimaryKeyColumn)})");

        return $"""
            CREATE TABLE IF NOT EXISTS {QuoteIdentifier(table.Name)} (
                {string.Join(",\n                ", lines)}
            );
            """;
    }

    private static string BuildCreateIndexSql(IndexSchema index, DatabaseProvider provider)
    {
        var uniqueSql = index.Unique ? "UNIQUE " : string.Empty;
        var indexName = SelectText(index.Name, provider);
        var indexTarget = index.Expression is null
            ? string.Join(", ", index.Columns.Select(QuoteIdentifier))
            : SelectText(index.Expression, provider);

        return $"""
            CREATE {uniqueSql}INDEX IF NOT EXISTS {QuoteIdentifier(indexName)}
            ON {QuoteIdentifier(index.TableName)} ({indexTarget});
            """;
    }

    private static string BuildColumnSql(TableSchema table, ColumnSchema column, DatabaseProvider provider)
    {
        var definition = provider == DatabaseProvider.Sqlite
            ? column.SqliteDefinition
            : column.PostgresDefinition;
        var columnSql = $"{QuoteIdentifier(column.Name)} {definition}";

        if (provider != DatabaseProvider.Sqlite || column.Name != table.PrimaryKeyColumn)
            return columnSql;

        var primaryKeySql = $" CONSTRAINT {QuoteIdentifier($"PK_{table.Name}")} PRIMARY KEY";
        return table.PrimaryKeyAutoIncrements
            ? $"{columnSql}{primaryKeySql} AUTOINCREMENT"
            : $"{columnSql}{primaryKeySql}";
    }

    private static async Task EnsureSqliteColumnAsync(AppDbContext context, string tableName, string columnName, string definition)
    {
        var connection = context.Database.GetDbConnection();
        var closeAfterUse = connection.State != System.Data.ConnectionState.Open;

        if (closeAfterUse)
            await connection.OpenAsync();

        try
        {
            if (await ColumnExistsAsync(connection, tableName, columnName))
                return;

            var sql = $"ALTER TABLE {QuoteIdentifier(tableName)} ADD COLUMN {QuoteIdentifier(columnName)} {definition};";
            await context.Database.ExecuteSqlRawAsync(sql);
        }
        finally
        {
            if (closeAfterUse)
                await connection.CloseAsync();
        }
    }

    private static async Task<bool> ColumnExistsAsync(DbConnection connection, string tableName, string columnName)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = $"PRAGMA table_info({QuoteIdentifier(tableName)});";

        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            if (string.Equals(reader.GetString(1), columnName, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    private static string SelectSql(ProviderSql sql, DatabaseProvider provider) =>
        provider == DatabaseProvider.Sqlite ? sql.Sqlite : sql.Postgres;

    private static string SelectText(ProviderText text, DatabaseProvider provider) =>
        provider == DatabaseProvider.Sqlite ? text.Sqlite : text.Postgres;

    private static string QuoteIdentifier(string identifier)
    {
        if (identifier.Length == 0 || identifier.Any(c => !char.IsAsciiLetterOrDigit(c) && c != '_'))
            throw new InvalidOperationException("Identificador SQL inválido.");

        return $"\"{identifier}\"";
    }
}
